### ISSUE TITLE
Request of SE4, SEK, and temp options with Shelly plus UNI and 3x DS18B20?

### ISSUE THREAD

**Issue by Bundas77** [LeivoSepp/Smart-heating-management-with-Shelly#1]
Hi,
I’m not a programmer, So I would like to ask you if you can help me? Is it possible to add SE4 and SEK to the script? I would like to run it on a Shelly Plus Uni, with 3x ds18b20 temperature sensors on my CTC EcoAir Polar Edition 107 heat pump, by putting a parallel resistor on the built in external temp sensor of the heat pump, to be able to fool the heat pump of the outside temperature, making it not starting, believing it is hot outside.
Further I’m interested in enabling/disabling the script if outside temperature is below x degrees Celsius (1xds18b20), or enable/disable it if the outgoing/incoming water temperatures differential (2xds18b20), is too high or too low, making it possible to emergency run it even if the price is too high. 
THX

**Comment by LeivoSepp** [comment]
I think the best way to achieve what you described is to use two Shellys:

* Primary Shelly: Configured with the script to control the heat pump during the cheapest time periods.
* Secondary Shelly: Set up with dry contacts to enable or disable the primary Shelly's ability to manage the heat pump.

This setup creates a simple and effective way to achieve your desired system architecture.

**Comment by LeivoSepp** [comment]
Adding support for SE4 and SEK zones requires onboarding the Entsoe API.
Since I haven’t encountered anyone using this with Shelly yet, implementing it may take some time.
