### ISSUE TITLE
Irregular timing for 24h update cycle.

### ISSUE THREAD

**Issue by kalleka** [LeivoSepp/Smart-heating-management-with-Shelly#3]
Hi. Nice script.
1. For a 24h calculation cycle the server update time alternates between 23:00 and 00:00. In the latter case that could potentially cause the task scheduled at 00:00 to be missed as the trigger event had already passed. By adding `isToday` check to `isTsAfterChkT` should prevent that.
2. All the clients are sending update requests to server during the first minute of an hour. Adding some random minutes to `isChkT` would reduce the server load in case the script turns out to be very popular :)
3. The next heating calculation time printed in the log was not correct (the current hour was reported instead). The proposed patch contains a modified `nextChkHr()` function that corrects the issue.

**Comment by LeivoSepp** [comment]
Appreciate your contribution.
Just merged the PR.
