### ISSUE TITLE
isOutputInverted: false issue

### ISSUE THREAD

**Issue by HardyVIIL** [LeivoSepp/Smart-heating-management-with-Shelly#5]
It seems that changing isOutputInverted to false does not change output behaviour. In created schedule control output switch0 state is set off.

 

code mod

let s = {
    heatingMode: HEAT24H_3H, // HEATING MODE. Different heating modes described above.
    elektrilevi: "VORK2",      // ELEKTRILEVI transmission fee: VORK1 / VORK2 / VORK4 /VORK5 / NONE
    alwaysOnLowPrice: 10,       // Keep heating always ON if energy price lower than this value (EUR/MWh)
    alwaysOffHighPrice: 300,    // Keep heating always OFF if energy price higher than this value (EUR/MWh)
    isOutputInverted: false,    // Configures the relay state to either normal or inverted. (inverted required by Nibe, Thermia)
    relayID: 0,                 // Shelly relay ID
    defaultTimer: 60,           // Default timer duration, in minutes, for toggling the Shelly state.
    country: "ee",              // Estonia-ee, Finland-fi, Lithuania-lt, Latvia-lv
    heatingCurve: 0,            // Shifting heating curve to the left or right, check the tables below. Shift by 1 equals 1h. 
    powerFactor: 0.5,           // Adjusts the heating curve to be either more flat or more aggressive (0 -> flat, 1 -> steep).
}

resulting output

<img width="1099" alt="Screenshot 2024-12-08 at 08 05 42" src="https://github.com/user-attachments/assets/0eae9e03-d933-4338-98b6-35cc81262243">

**Comment by HardyVIIL** [comment]
Commenting out isOutputInverted line fixes the issue.

**Comment by LeivoSepp** [comment]
Please change the configuration setting from the Shelly KVS store https://github.com/LeivoSepp/Smart-heating-management-with-Shelly?tab=readme-ov-file#configuring-script-parameters.


All default settings are stored in KVS, and modifying the settings later directly in the code will have no impact.

**Comment by LeivoSepp** [comment]
Configuration settings can only be changed through the Shelly KVS store. 
The reason for this is that updating the script to the newer version becomes straightforward — just copy-paste the code, and all the settings are automatically pulled from the KVS.
